[package]
name = "hello-world"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"

[dependencies.shuttle-service]
version = "0.4.0"
features = ["web-actix-web"]
path = "../../../service"
