[package]
name = "shuttle-runtime"
version = "0.42.0"
edition.workspace = true
license.workspace = true
description = "Runtime to start and manage any service that runs on shuttle"

[lib]
doctest = false

[dependencies]
shuttle-codegen = { workspace = true }
shuttle-common = { workspace = true, features = ["extract_propagation"] }
shuttle-proto = { workspace = true, features = ["runtime"] }
shuttle-service = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
colored = { workspace = true, optional = true }
prost-types = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
strfmt = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tokio-stream = { workspace = true }
tonic = { workspace = true }
tracing-subscriber = { workspace = true, optional = true }
reqwest = { workspace = true, default-features = false, features = ["rustls-tls"] }

[dev-dependencies]
portpicker = "0.1.1"
shuttle-service = { workspace = true, features = ["builder", "runner"] }
shuttle-proto = { workspace = true, features = ["provisioner"] }
uuid = { workspace = true }

[features]
default = ["setup-tracing"]

setup-tracing = [
    "tracing-subscriber/default",
    "tracing-subscriber/env-filter",
    "colored",
]
